/* Newslleter customizada para a plataforma VTEX // 4.3 // Carlos Vinicius [ QUATRO DIGITAL ] // Todos os Direitos Reservados */
"function"!==typeof String.prototype.trim&&(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});
(function(h){"function"!==typeof h.fn.QD_news&&(h.fn.QD_news=function(q){var g,a,n,k;k=function(a,b){"object"===typeof console&&("undefined"!==typeof b&&"alerta"===b.toLowerCase()?console.warn("[VtexNews] "+a):"undefined"!==typeof b&&"info"===b.toLowerCase()?console.info("[VtexNews] "+a):console.error("[VtexNews] "+a))};g=jQuery(this);if(1>g.length)return g;a=jQuery.extend({defaultName:"Digite seu nome...",defaultEmail:"Digite seu e-mail...",nameField:".vtexNewsName",emailField:".vtexNewsEmail",btn:".vtexNewsButton",
elementError:".nv2_messageError",elementSuccess:".nv2_messageSuccess",validationMethod:"popup",getAttr:"alt",setDefaultName:!0,checkNameExist:!0,showInPopup:!0,animation:"blink",animateSpeed:100,animateDistance:15,animateRepeat:3,animateFieldSuccess:".vtexNewsAnimateFieldSuccess",timeHideSuccessMsg:3E3,successCallback:function(){},submitCallback:function(a,b){}},q);a.showInPopup||(a.validationMethod="div");null!==a.animation?a.validationMethod="animateField":"animateField"==a.validationMethod&&(a.animation=
"leftRight");if("popup"==a.validationMethod&&"function"!==typeof jQuery.fn.vtexPopUp2)return k("O popUp2 n\u00e3o foi encontrado. Adicione o Plugin de PopUp2."),g;n=function(f){var b,e,c;e=0;b=function(){f.animate({left:"-="+a.animateDistance},a.animateSpeed,function(){f.animate({left:"+="+a.animateDistance},a.animateSpeed,function(){e<a.animateRepeat&&b();e++})})};c=function(){f.fadeTo(a.animateSpeed,0.2,function(){f.fadeTo(a.animateSpeed,1,function(){e<a.animateRepeat&&c();e++})})};f.stop(!0,!0);
"leftRight"==a.animation?b():"blink"==a.animation&&c()};g.each(function(){var f,b,e,c,g,l,m;b=jQuery(this);e=b.find(a.nameField);c=b.find(a.emailField);g=b.find(a.btn);l=b.find(a.elementError);m=b.find(a.elementSuccess);1>e.length&&a.checkNameExist&&k("Campo de nome, n\u00e3o encontrado ("+e.selector+"). Ser\u00e1 atribuido um valor padr\u00e3o.","info");if(1>c.length)return k("Campo de e-mail, n\u00e3o encontrado ("+c.selector+")"),b;if(1>g.length)return k("Bot\u00e3o de envio, n\u00e3o encontrado ("+
g.selector+")"),b;if("animateField"!=a.validationMethod&&(1>m.length||1>l.length))return k("A(s) mensagem(ns) de erro e/ou sucesso esta(m) faltando \n ("+m.selector+", "+l.selector+")"),b;a.setDefaultName&&e.is("input[type=text], textarea")&&e.val(a.defaultName);c.val(a.defaultEmail);(function(){var d,b;a.checkNameExist&&(d=e.filter(":visible"),d.length&&(b=d.val(),e.is("input, textarea")&&d.bind({focus:function(){d.val()!=b||0!==d.val().search(a.defaultName.substr(0,6))&&!a.setDefaultName||d.val("")},
blur:function(){""===d.val()&&d.val(b)}})))})();(function(){var b;b=c.val();c.bind({focus:function(){c.val()==b&&0===c.val().search(a.defaultEmail.substr(0,6))&&c.val("")},blur:function(){""===c.val()&&c.val(b)}})})();f=function(){var d,c,e,f;c=(d=b.find(a.nameField).filter("input[type=text],select,textarea").val())?d:(d=b.find(a.nameField).filter("input[type=radio]:checked, input[type=checkbox]:checked").val())?d:(d=b.find(a.nameField).attr(a.getAttr))?d:(d=b.find(a.nameField).text())?d:(d=b.find(a.nameField).find(".box-banner img:first").attr("alt"))?
d:"Nome_Padrao";d=(b.find(a.emailField).val()||"").trim();e=b.find(a.nameField).is(":visible");e=(1>c.length||0===c.search(a.defaultName.substr(0,6)))&&(a.checkNameExist||e?e:!0);f=0>d.search(/^[a-z0-9\_\-\.]+@[a-z0-9\_\-]+(\.[a-z0-9\_\-]{2,})+$/i);e||f?"animateField"==a.validationMethod?(e&&n(b.find(a.nameField)),f&&n(b.find(a.emailField))):"popup"==a.validationMethod?l.vtexPopUp2({popupType:"newsletter",popupClass:"popupNewsletterError"}):(l.slideDown().bind("click",function(){h(this).slideUp()}),
setTimeout(function(){l.slideUp()},1800)):(g.attr("disabled","disabled"),jQuery.ajax({url:"/no-cache/Newsletter.aspx",type:"POST",data:{newsletterClientEmail:d,newsletterClientName:c,newsInternalCampaign:"newsletter:opt-in",newsInternalPage:(document.location.pathname||"/").replace(/\//g,"_"),newsInternalPart:"newsletter"},success:function(d){var c,e,f;g.removeAttr("disabled");"popup"==a.validationMethod?m.vtexPopUp2({popupType:"newsletter",popupClass:"popupNewsletterSuccess"}):"animateField"!=a.validationMethod&&
m.slideDown().bind("click",function(){h(this).slideUp()});f=b.find(a.emailField);a.setDefaultName&&b.find(a.nameField).is("input, textarea")&&b.find(a.nameField).val(a.defaultName);c=function(){f.val(a.defaultEmail)};"animateField"==a.validationMethod?(f.val(b.find(a.animateFieldSuccess).val()||"Obrigado!!!"),f.addClass("vtexNewsSuccess"),e=setTimeout(function(){f.removeClass("vtexNewsSuccess");c();f.unbind("focus.vtexNews")},a.timeHideSuccessMsg),f.bind("focus.vtexNews",function(){f.removeClass("vtexNewsSuccess");
clearTimeout(e);h(this).val("");h(this).unbind("focus.vtexNews")})):c();a.successCallback()}}),a.submitCallback(d,c))};g.bind("click",function(){f()});var p=function(a){13==(a.keyCode?a.keyCode:a.which)&&(a.preventDefault(),f())};e.filter("input, textarea").bind("keydown",p);c.bind("keydown",p)});return g},h(function(){h(".qd_news_auto").QD_news()}))})(jQuery);
/**
* Vtex Gift List
* @author Carlos Vinicius
* @version 1.5
* @date 2012-09-18
*/
jQuery.fn.vtexGiftlist=function(d){var e=jQuery(this);if(1>e.length)return e;var g=jQuery.extend({giftListWrap:".giftListWrap",popupShow:function(){},buyBtnFormat:function(a,c){var f=jQuery('<div class="giftListBtn"></div>'),b=jQuery('<div class="skuTplButtonsWrap"></div>');a.after(b);a.appendTo(b);c.appendTo(f);f.appendTo(b)}},d),d=jQuery("body");jQuery("");var a=d.find(g.giftListWrap),j="object"==typeof console;if(1>a.length)return j&&console.log("Elemento contendo o controle de lista n\u00e3o encontrado ("+
a.selector+")"),!1;var k=a.parent(),i=d.find("div.skuList"),h={actions:function(d){var c=d||e;c.bind("click",function(){var f,b;f=a.find(".giftlistcreate-nouser");a.find(".giftlistinsertsku").show();b=a.find(".giftlistinsertsku-message");if("block"==b.css("display"))return alert(b.text());b.css("display","block").hide();c.hasClass("multipleSkus")&&a.find(".giftlistinsertsku-button").each(function(){var a=jQuery(this),b=(a.attr("href")||"").split(",");b[1]="'"+c.attr("rel")+"'";a.attr("href",b.join(","))});
if(1>f.length)a.vtexPopUp2({initCallback:g.popupShow,closeCallback:function(){a.appendTo(k)}});else return alert("Voc\u00ea precisa estar logado para adicionar um item a lista."),document.location.href="https://"+document.location.host+"/Site/Login.aspx?ReturnUrl="+document.location.pathname,!1})},buyButton:function(){var a=i.find(".buy-button");if(1>a.length||2>i.length)return!1;var c=e.clone().addClass("multipleSkus");a.each(function(){var a=c.clone(),b=jQuery(this);g.buyBtnFormat(b,a);a.attr("rel",
(b.attr("href")||"").split("Sku=").pop());h.actions(a)});e.hide()}};h.actions();h.buyButton();return e};
/**
* PopUps
* @author Carlos Vinicius
* @version 1.22
* @date 2012-08-24
*/
jQuery.fn.vtexPopUp2=function(l){var j=jQuery(this);if(1>j.length)return j;var i=jQuery("body"),d=i.find(".boxPopUp2"),k="object"==typeof console;1>d.length&&(d=jQuery('<div class="boxPopUp2"><div class="boxPopUp2-wrap"><span class="boxPopUp2-close"></span><div class="boxPopUp2-content"></div></div></div>'),i.prepend(d),d.after('<div class="boxPopUp2-overlay"></div>'));var c=jQuery.extend({popupType:null,closeContent:null,popupClass:"",quickViewClass:".quickViewLink",initCallback:function(){},closeCallback:function(){}},
l),l=d.find(".boxPopUp2-close"),f=d.find(".boxPopUp2-content"),m=i.find(".boxPopUp2-close, .boxPopUp2-overlay"),n=i.find(".boxPopUp2-overlay"),h=jQuery(document);null!=c.closeContent&&l.html(c.closeContent);var b={positioning:function(){var a=h.scrollTop(),b=jQuery(window).height(),c=d.outerHeight(!0);d.css("top",a+(c>=b?20:(b-c)/2)+"px")},show:function(a){a=a||{};n.fadeTo("fast",0.5,function(){d.show().addClass("popupOpened");"boolean"===typeof a.loading&&!0===a.loading?b.showLoading():b.hideLoading();
"function"===typeof a.callback?a.callback():c.initCallback(d)})},hideLoading:function(){f.filter(":visible").css("background-image","none")},showLoading:function(){f.filter(":visible").css("background-image",'url("/arquivos/ajax-loader.gif")')},close:function(a){var a=a||{},b=function(){n.fadeOut("fast");d.fadeOut("fast",function(){f.empty()});f.attr("class","boxPopUp2-content");d.attr("class","boxPopUp2")};"boolean"==typeof a.closeNow&&!0==a.closeNow&&b();1>m.filter(".boxPopUp2-clickActive").length&&
(m.addClass("boxPopUp2-clickActive").bind("click",function(){"function"===typeof a.clickCallback?a.clickCallback():c.closeCallback(d);b()}),h.bind("keyup",function(a){27==(a.keyCode?a.keyCode:a.which)&&b()}));if(j.hasClass("autoClose")){var g=(j.attr("class")||"").split("ac_").pop().split(" ").shift();if(isNaN(parseFloat(g)))return k&&console.log("[Erro] O tempo informado (em segundos) n\u00e3o \u00e9 um valor num\u00e9rico: \u201c"+g+"\u201d"),!1;setTimeout(function(){b()},1E3*g)}},setType:function(a){if(a.hasClass("quickViewLink"))b.quickView(a);
else if(a.hasClass("giftListWrap"))b.giftList(a);else if(a.hasClass("installmentInfoTpl"))b.paymentForms(a);else if(a.hasClass("shipping-value"))b.calculateShipping(a);else if(a.hasClass("freeContent"))b.freeContent(a);else if(a.hasClass("boxPopUp2"))b.closeNow(a);else if(a.hasClass("referAFriendTpl"))b.productReferAFriend(a);else if(0<a.filter("#btnReferAFriend").length)b.giftListReferFriend(a);else if(0<a.filter("#lnkPubliqueResenha").length)b.postRatingComment(a);else if(0<a.filter("#palerta").length)b.cartCheckoutAlert(a);
else if(a.hasClass("lnkAddPhoto"))c.popupType="minhaContaFoto",b.userAccount(a);else return!1},checkType:function(a){"cadastroCliente"===c.popupType||"minhaContaFoto"===c.popupType?b.userAccount(a):"newsletter"===c.popupType?b.newsletter(a):"quickview"===c.popupType?b.quickView(a):"giftlist"===c.popupType?b.giftList(a):"paymentforms"===c.popupType?b.paymentForms(a):"shipping"===c.popupType?b.calculateShipping(a):"string"==typeof c.popupType&&"freecontent"===c.popupType.toLowerCase()?b.freeContent(a):
"closenow"===c.popupType?b.closeNow(a):"GiftListReferAFriend"===c.popupType?b.giftListReferFriend(a):"postRatingComment"===c.popupType?b.postRatingComment(a):b.freeContent(a)},exec:function(){j.each(function(){var a=$(this);null===c.popupType?b.setType(a):!1===b.checkType(a)&&b.setType(a)});c.initCallback()},userAccount:function(a){var e="";"cadastroCliente"===c.popupType?e="signInPopups":"minhaContaFoto"===c.popupType&&(e="profilePhoto");a.unbind().removeAttr("onclick");var g=a.attr("href")||"";
a.bind("mouseenter",function(){a.unbind().bind("click",function(){d.addClass(c.popupClass+" "+e+"Main");""===g&&k&&console.log("N\u00e3o existe URL no atributo href");jQuery('<iframe src="'+g+'" frameborder="0" allowtransparency="true"></iframe>').appendTo(f.addClass(c.popupClass+" "+e));b.show({loading:!0});b.positioning();b.close();return!1})})},newsletter:function(a){a.clone().appendTo(f.addClass(c.popupClass+" newsletterPopup"));d.addClass(c.popupClass+" newsletterMain");b.show();b.positioning();
b.close()},quickView:function(a){var a=i.find(c.quickViewClass),e=function(){a.filter(":not(.quickViewLinkActivated)").addClass("quickViewLinkActivated").bind("click",function(){jQuery('<iframe src="'+jQuery(this).attr("href")+'" frameborder="0" allowtransparency="true"></iframe>').appendTo(f.addClass(c.popupClass+" productQuickView"));d.addClass(c.popupClass+" quickViewMain");b.show({loading:!0});b.positioning();b.close();return!1})};e();h.ajaxStop(e)},paymentForms:function(a){var e="",g=function(){var a=
i.find(".see-other-payment-method-link");if(1>a.length)return k&&console.log("Url das formas de pagamento n\u00e3o encontrado. \n Verifique se o controle esta na p\u00e1gina.\n("+a.selector+")"),!1;e=/http:(.*?)(?=\&)/.exec(a[0].getAttribute("onclick").toString())[0]||"#onclickError"};g();a.bind("click",function(){jQuery("<iframe src='"+e+"' frameborder='0' allowtransparency='true'></iframe>").appendTo(f.addClass(c.popupClass+" paymentFormsPopup"));d.addClass(c.popupClass+" paymentFormsMain");b.show({loading:!0});
b.positioning();b.close();return!1});h.ajaxStop(g)},calculateShipping:function(){h.ajaxStop(function(){var a=i.find("#calculoFrete").children();if(1>a.length)return!1;a.find("span.cep-busca a").attr("target","_blank");a.appendTo(f.addClass(c.popupClass+" shippingCalculationPopup"));d.addClass(c.popupClass+" shippingCalculationMain");b.show();b.positioning();b.close()})},giftList:function(a){a.appendTo(f.addClass(c.popupClass+" giftListPopup"));d.addClass(c.popupClass+" giftListMain");b.show();b.positioning();
b.close({clickCallback:c.closeCallback})},cartCheckoutAlert:function(a){a.appendTo(f.addClass(c.popupClass+" cartCheckoutAlertPopup"));d.addClass(c.popupClass+" cartCheckoutAlertMain");b.show();b.positioning();b.close()},freeContent:function(a){a.appendTo(f.addClass(c.popupClass+" freeContentPopup"));d.addClass(c.popupClass+" freeContentMain");b.show();b.positioning();b.close()},closeNow:function(){b.close({closeNow:!0})},giftListReferFriend:function(a){var e=function(){var a=$(this).attr("href");
if("undefined"===typeof a||""===a)return k&&console.log("[Erro] Url do popup n\u00e3o encontrada."),!1;f.addClass(c.popupClass+" freeContentPopup").load(a);d.addClass(c.popupClass+" giftListReferFriendMain");b.show({loading:!0});b.positioning();b.close();return!1},g=function(){a.unbind().bind("mouseenter",function(){a.unbind().bind("click",e)})};g();h.ajaxStop(g)},productReferAFriend:function(a){var e=jQuery('<div class="referAFriendPopUpWrap"></div>');a.bind("click",function(){var a=(jQuery(this).parent().find("#div-referAFriend input").attr("onclick")||
"").toString(),a=/\/referAFriend\/Form\/[0-9]+\?/i.exec(a);if(null===a)return alert("Desculpe, n\u00e3o foi poss\u00edvel abrir o formul\u00e1rio."),!1;e.empty().load(a[0],function(){b.positioning()});e.appendTo(f.addClass(c.popupClass+" freeContentPopup"));d.addClass(c.popupClass+" freeContentMain");b.show();b.positioning();b.close();return!1});h.ajaxStop(function(){0<f.find(".referAFriendPopUpWrap #btnFechar").length&&setTimeout(b.closeNow,1500)})},postRatingComment:function(a){var a=a.filter(":not(.popUpPublishReviewActivated)"),
e=!1;if(1>a.length)return!1;a.bind("click",function(){var a=jQuery(this).attr("href")||"";if(""===a)return k&&console.log("[Erro] N\u00e3o foi poss\u00edvel obter os dados para abrir o popup de resenha."),!1;a=a.split(")").shift().split("(").pop().split(",");if(3!=a.length)return k&&console.log("[Erro] O array com os dados do cliente retornou um valor inesperado."),!1;if(e)return!1;e=!0;jQuery.ajax({url:"/publishuserreviewcomment",type:"POST",data:{productId:a[1],clientId:a[0],categoryId:a[2]},success:function(a){var g=
jQuery(a);f.addClass(c.popupClass+" userReviewPopup").html(g);d.addClass(c.popupClass+" userReviewPopupMain");b.show({callback:function(){g.find("#txtTituloResenha:hidden").val("titulo_auto");var a=f.find("a#rtAvaliacao_A0"),b=function(){a.attr("title",a.find(".filledRatingStar:last").index()+1||0)};a.find("span").bind("mouseenter",b);a.bind("mouseleave",b)}});b.positioning();b.close();e=!1},error:function(){e=!1}});return!1}).addClass("popUpPublishReviewActivated");0==jQuery.fn.vtexPopUp2.data.userReviewCount&&
h.ajaxStop(function(){f.hasClass("userReviewPopup")&&0==f.find(".formUserComment").children().length&&b.closeNow()});jQuery.fn.vtexPopUp2.data.userReviewCount++}};b.exec();return j};jQuery.fn.vtexPopUp2.data={userReviewCount:0};

// AUTOLOADS
$(function(){
	var b=$("body");
	
	
	/* Carriho */
	// $(".cartWrapper").addClass("smart_checkout").append('<span class="qd_cart_total"></span> <span class="qd_cart_qtt"></span> <span class="qd_items_text plural">Itens</span><span class="qd_items_text singular">Item</span>').simpleCart();
	
	
	/* Gift List */ b.find(".giftListButtonTpl").vtexGiftlist();
	/* Newsletter */ b.find(".vtexNewsWrap").QD_news();
	// /* Quickview */ b.find(".quickViewLink").vtexPopUp2();
	/* Formas de pagamento */ b.find(".installmentInfoTpl").vtexPopUp2();
	/* C�lculo de frete */ b.find(".shipping-value").vtexPopUp2();
	// /* Indicar a um amigo (P�g. Listas Gerenciar) */ b.find("td.giftlist-body-action-sendfriend #btnReferAFriend").vtexPopUp2();
	// /* Minha conta - alterar foto */ b.filter(".minha-conta").find(".lnkAddPhoto").vtexPopUp2();
	// /* cadastro */ b.filter(".cadastro-cliente").find(".thickbox").vtexPopUp2({"popupType":"cadastroCliente"});
	/* Indicar � um amigo (pg. Produto) */ b.find(".referAFriendTpl").vtexPopUp2();
});
$(document).ajaxStop(function(){
	var b=$("body");
	/* Publicar coment�rio sobre o produto */ b.find("#lnkPubliqueResenha[href*='javascript']").vtexPopUp2();
	/* Quickview */ b.find(".quickViewLink").vtexPopUp2();
});